/**
 * LaTeX Compiler with Hybrid Local + Online Support
 *
 * Strategy:
 * 1. Try local LaTeX compiler first (if installed)
 * 2. Fall back to online compilation if local not available
 * 3. Show user which mode is being used
 */

import * as cp from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import * as vscode from 'vscode';
import * as https from 'https';

export interface CompilationResult {
    success: boolean;
    pdfPath?: string;
    error?: Error;
    mode: 'local' | 'online';
    message: string;
}

/**
 * Check if LaTeX is installed locally
 */
async function isLatexInstalled(latexPath: string): Promise<boolean> {
    return new Promise((resolve) => {
        cp.exec(`${latexPath} --version`, (error) => {
            resolve(!error);
        });
    });
}

/**
 * Compile using local LaTeX installation
 */
async function compileLocal(
    latexPath: string,
    tempDir: string,
    tempFile: string
): Promise<CompilationResult> {
    return new Promise((resolve) => {
        cp.exec(
            `${latexPath} -interaction=nonstopmode -output-directory="${tempDir}" "${tempFile}"`,
            (error) => {
                if (error) {
                    resolve({
                        success: false,
                        error,
                        mode: 'local',
                        message: `LaTeX compilation failed: ${error.message}`
                    });
                } else {
                    const pdfPath = path.join(tempDir, 'temp.pdf');
                    if (fs.existsSync(pdfPath)) {
                        resolve({
                            success: true,
                            pdfPath,
                            mode: 'local',
                            message: 'Compiled successfully (Local LaTeX)'
                        });
                    } else {
                        resolve({
                            success: false,
                            error: new Error('PDF file not generated'),
                            mode: 'local',
                            message: 'PDF file not generated by LaTeX compiler'
                        });
                    }
                }
            }
        );
    });
}

/**
 * Compile using online LaTeX service (pdflatex.online)
 */
async function compileOnline(
    texContent: string,
    tempDir: string
): Promise<CompilationResult> {
    return new Promise((resolve) => {
        const payload = JSON.stringify({
            compiler: 'pdflatex',
            resources: [
                {
                    main: true,
                    filename: 'main.tex',
                    content: texContent
                }
            ]
        });

        const options = {
            hostname: 'pdflatex.online',
            port: 443,
            path: '/api/v1/create',
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Content-Length': Buffer.byteLength(payload)
            },
            timeout: 30000
        };

        try {
            const req = https.request(options, (res: any) => {
                let data = '';

                res.on('data', (chunk: any) => {
                    data += chunk;
                });

                res.on('end', () => {
                    try {
                        const response = JSON.parse(data);

                        if (response.status === 'success' && response.pdf) {
                            // Decode base64 PDF and save to file
                            const pdfBuffer = Buffer.from(response.pdf, 'base64');
                            const pdfPath = path.join(tempDir, 'temp.pdf');
                            fs.writeFileSync(pdfPath, pdfBuffer);

                            resolve({
                                success: true,
                                pdfPath,
                                mode: 'online',
                                message: 'Compiled successfully (Online LaTeX - No local distro detected)'
                            });
                        } else {
                            const errorMsg = response.error || 'Unknown error from online service';
                            resolve({
                                success: false,
                                error: new Error(errorMsg),
                                mode: 'online',
                                message: `Online compilation failed: ${errorMsg}`
                            });
                        }
                    } catch (parseError) {
                        resolve({
                            success: false,
                            error: new Error(`Failed to parse response: ${data}`),
                            mode: 'online',
                            message: 'Failed to parse online compilation response'
                        });
                    }
                });
            });

            req.on('error', (error: any) => {
                resolve({
                    success: false,
                    error,
                    mode: 'online',
                    message: `Online compilation error: ${error.message}`
                });
            });

            req.on('timeout', () => {
                req.destroy();
                resolve({
                    success: false,
                    error: new Error('Online compilation timeout'),
                    mode: 'online',
                    message: 'Online compilation timed out (30s). Check internet connection.'
                });
            });

            req.write(payload);
            req.end();
        } catch (error) {
            resolve({
                success: false,
                error: error as Error,
                mode: 'online',
                message: `Failed to start online compilation: ${(error as Error).message}`
            });
        }
    });
}

/**
 * Compile LaTeX using hybrid approach:
 * 1. Try local compilation first
 * 2. Fall back to online if local not available
 */
export async function compileLatex(
    latexPath: string,
    tempDir: string,
    tempFile: string,
    texContent: string,
    enableOnlineFallback: boolean = true
): Promise<CompilationResult> {
    // Ensure temp directory exists
    if (!fs.existsSync(tempDir)) {
        fs.mkdirSync(tempDir, { recursive: true });
    }

    // Try local compilation first
    const isInstalled = await isLatexInstalled(latexPath);

    if (isInstalled) {
        const result = await compileLocal(latexPath, tempDir, tempFile);
        if (result.success) {
            return result;
        }
        // If local fails and online fallback is enabled, try online
        if (!enableOnlineFallback) {
            return result;
        }
    }

    // Fall back to online compilation
    if (enableOnlineFallback) {
        return await compileOnline(texContent, tempDir);
    }

    // No online fallback enabled
    return {
        success: false,
        error: new Error('LaTeX not found locally and online fallback disabled'),
        mode: 'local',
        message: 'LaTeX compiler not found. Install TeX Live, MiKTeX, or MacTeX, or enable online compilation in settings.'
    };
}

/**
 * Show compilation mode notification to user
 */
export function notifyCompilationMode(result: CompilationResult) {
    if (result.mode === 'online') {
        vscode.window.showInformationMessage(
            '📡 Using online LaTeX compilation (no local distro detected). Privacy: Your .tex file is sent to pdflatex.online for compilation.',
            'OK',
            'Disable Online Fallback'
        ).then(selection => {
            if (selection === 'Disable Online Fallback') {
                vscode.workspace.getConfiguration('texmex').update(
                    'enableOnlineFallback',
                    false,
                    vscode.ConfigurationTarget.Global
                );
            }
        });
    }
}

/**
 * Check LaTeX installation at extension startup
 */
export async function checkLatexInstallation(latexPath: string): Promise<boolean> {
    const installed = await isLatexInstalled(latexPath);

    if (!installed) {
        const enableOnlineFallback = vscode.workspace.getConfiguration('texmex').get('enableOnlineFallback', true);

        if (enableOnlineFallback) {
            vscode.window.showWarningMessage(
                '📡 LaTeX not found. Will use online compilation as fallback. Install LaTeX for better performance.',
                'Install LaTeX Guide',
                'Use Online Only',
                'Install Locally'
            ).then(selection => {
                if (selection === 'Install LaTeX Guide') {
                    vscode.env.openExternal(
                        vscode.Uri.parse('https://www.tug.org/texlive/')
                    );
                } else if (selection === 'Use Online Only') {
                    // User confirmed they want online only
                }
            });
        } else {
            vscode.window.showErrorMessage(
                'LaTeX not found and online fallback is disabled. Install LaTeX or enable online fallback in settings.'
            );
        }
    }

    return installed;
}
